# Generated by Django 4.2.4 on 2026-01-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Producto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=200, unique=True)),
                ("nombre", models.CharField(max_length=1000)),
                ("categoria", models.CharField(blank=True, max_length=400, null=True)),
                ("compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ingreso", models.IntegerField(default=0)),
                ("salida", models.IntegerField(default=0)),
                ("estado", models.BooleanField(default=1)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-codigo"],
            },
        ),
    ]
