# Generated by Django 4.2.4 on 2026-01-13 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=1000)),
                ('tel', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('compras', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.BooleanField(default=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-nit'],
            },
        ),
    ]
