# Generated by Django 4.2.4 on 2026-01-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proveedor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="fecha",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
