# Generated by Django 4.2.4 on 2026-01-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
