# Generated by Django 4.2.27 on 2026-02-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_alter_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
    ]
