# Generated by Django 4.2.27 on 2026-01-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_producto2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
    ]
