# Generated by Django 4.2.4 on 2026-01-24 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Producto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("factura", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nit",
                    models.CharField(
                        blank=True, default="CF", max_length=15, null=True
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Proforma", "Proforma"),
                            ("FEL", "FEL"),
                            ("Cotizacion", "Cotizacion"),
                        ],
                        max_length=50,
                    ),
                ),
                ("link", models.URLField(blank=True, max_length=250, null=True)),
                ("numero", models.BigIntegerField(blank=True, null=True)),
                ("serie", models.CharField(blank=True, max_length=100, null=True)),
                ("anula", models.TextField(blank=True, null=True)),
                ("fecha_fel", models.DateTimeField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=12
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.IntegerField(
                        choices=[(0, "Pendiente"), (1, "Procesada"), (2, "Anulada")],
                        default=0,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["factura"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Producto.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Venta.venta"
                    ),
                ),
            ],
            options={
                "ordering": ["venta"],
            },
        ),
        migrations.AddConstraint(
            model_name="detalleventa",
            constraint=models.UniqueConstraint(
                fields=("venta", "producto"), name="unique_producto_por_venta"
            ),
        ),
    ]
