# Generated by Django 4.2.4 on 2026-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Venta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="lugar",
            field=models.CharField(
                choices=[("Bodega 1", "Bodega 1"), ("Bodega 2", "Bodega 2")],
                default="Bodega 1",
                max_length=50,
            ),
        ),
    ]
