# Generated by Django 4.2.27 on 2026-01-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_venta_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_actualizo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
