# Generated by Django 4.2.27 on 2026-01-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_bitacoraprecio'),
        ('Venta', '0003_detalleventa_fecha_actualizo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha_actualizo', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto2')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venta.venta')),
            ],
            options={
                'ordering': ['venta'],
            },
        ),
        migrations.AddConstraint(
            model_name='detalleventa2',
            constraint=models.UniqueConstraint(fields=('venta', 'producto'), name='unique_producto_por_venta_2'),
        ),
    ]
