# Generated by Django 4.2.27 on 2026-04-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0004_detalleventa2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
