# Generated by Django 4.1.7 on 2024-03-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
