# Generated by Django 4.1.7 on 2024-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
