# Generated by Django 4.2.6 on 2024-03-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='descanso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='turno',
        ),
    ]
