# Generated by Django 4.2.4 on 2025-08-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_descanso_remove_user_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='puesto',
        ),
    ]
