# Generated by Django 4.2.4 on 2026-01-24 21:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Producto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abastecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factura", models.CharField(max_length=200, unique=True)),
                ("fecha_factura", models.DateField()),
                ("proveedor", models.CharField(max_length=15)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("lugar", models.CharField(default="Tienda", max_length=50)),
                ("estado", models.BooleanField(default=1)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-factura"],
            },
        ),
        migrations.CreateModel(
            name="Detalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compra_antes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "compra_ahora",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "venta_antes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "venta_ahora",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("ingreso_antes", models.IntegerField(default=0)),
                ("ingreso_ahora", models.IntegerField(default=0)),
                ("estado", models.BooleanField(default=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "abastecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Abastecer.abastecer",
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Producto.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-abastecedor__fecha_factura"],
            },
        ),
    ]
